name = "RackVM Showcase"
kernel = "assets/vmlinuz"
initrd = "assets/initramfs"
memory = 512
cpus = 2
cmdline = "console=ttyS0,115200n8 earlyprintk=serial,ttyS0,115200 panic=-1 reboot=k rdinit=/init"
interactive = true
